### ISSUE TITLE
Multiplication example raises an error

### ISSUE THREAD

**Issue by nono2357** [hkhetawat/QArithmetic#1]
Using Python 3.6.9 and Qiskit 0.14.0, the multiplication example `examples/test_mult.py` raises an error:
```
$ python3 examples/test_mult.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/qiskit/circuit/quantumcircuit.py", line 405, in _bit_argument_conversion
    index] for index in bit_representation]
  File "/usr/local/lib/python3.6/dist-packages/qiskit/circuit/quantumcircuit.py", line 405, in <listcomp>
    index] for index in bit_representation]
TypeError: list indices must be integers or slices, not QuantumRegister

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/test_mult.py", line 24, in <module>
    mult(qc, a, b, m, N)
  File "/home/renaud/installations/QArithmetic/examples/QArithmetic.py", line 247, in mult
    cadd(circ, a[i], b, sub_qr(c, i, n+i), n)
  File "/home/renaud/installations/QArithmetic/examples/QArithmetic.py", line 100, in cadd
    cqft(circ, c, b, n)
  File "/home/renaud/installations/QArithmetic/examples/qft.py", line 43, in cqft
    circ.ch(p, q[i-1])
  File "/usr/local/lib/python3.6/dist-packages/qiskit/extensions/standard/ch.py", line 79, in ch
    return self.append(CHGate(), [ctl, tgt], [])
  File "/usr/local/lib/python3.6/dist-packages/qiskit/circuit/quantumcircuit.py", line 458, in append
    expanded_qargs = [self.qbit_argument_conversion(qarg) for qarg in qargs or []]
  File "/usr/local/lib/python3.6/dist-packages/qiskit/circuit/quantumcircuit.py", line 458, in <listcomp>
    expanded_qargs = [self.qbit_argument_conversion(qarg) for qarg in qargs or []]
  File "/usr/local/lib/python3.6/dist-packages/qiskit/circuit/quantumcircuit.py", line 427, in qbit_argument_conversion
    return QuantumCircuit._bit_argument_conversion(qubit_representation, self.qubits)
  File "/usr/local/lib/python3.6/dist-packages/qiskit/circuit/quantumcircuit.py", line 413, in _bit_argument_conversion
    type(bit_representation)))
qiskit.circuit.exceptions.CircuitError: "Type error handling (QuantumRegister(6, 'q2'), 2) (<class 'tuple'>)"
```

**Comment by nono2357** [comment]
Error is corrected in latest Qiskit (version 0.14.0) replacing:
```
def sub_qr(qr, x, y):
    sub = []
    for i in range (x, y+1):
        sub = sub + [(qr, i)]
    return sub
```

with:

```
def sub_qr(qr, x, y):
    sub = []
    for i in range (x, y+1):
        sub = sub + [qr[i]]
    return sub
```

**Comment by supersimple33** [comment]
I have addressed this in my addition of the controlled multiplication circuit in #2.

**Comment by thomasgwong** [comment]
Fixed with most recent merge from supersimple33.
